// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYeRbdcDIK6Q7gXGjgoqSdQ3_6AZ3ClnI',
    appId: '1:655484453321:web:10781c6150581a8952a818',
    messagingSenderId: '655484453321',
    projectId: 'learn-widgets',
    authDomain: 'learn-widgets.firebaseapp.com',
    storageBucket: 'learn-widgets.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUMxAXvR1RPhNiIVnupdCqo1HstRmIr5I',
    appId: '1:655484453321:android:4e0aad2508b9249252a818',
    messagingSenderId: '655484453321',
    projectId: 'learn-widgets',
    storageBucket: 'learn-widgets.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDW4bWvaMpO2sAjMLQoeQFNWDY7mZHc0m0',
    appId: '1:655484453321:ios:fbf596f9d018c54e52a818',
    messagingSenderId: '655484453321',
    projectId: 'learn-widgets',
    storageBucket: 'learn-widgets.appspot.com',
    iosClientId: '655484453321-kb2d4j1tq7uhvlbap7igncuaig8crjos.apps.googleusercontent.com',
    iosBundleId: 'sdf',
  );
}
